"""Mergeability metrics module for predicting model merging outcomes."""

from model_merging.metrics.mergeability import (
    METRIC_REGISTRY,
    compute_metric,
    compute_all_metrics,
    compute_metric_per_layer,
    compute_metric_layer_wise_avg,
    flatten_task_dict,
    task_vector_cosine_similarity,
    task_vector_l2_distance,
    task_vector_dot_product,
    weight_space_angle,
    task_vector_magnitude_ratio,
    singular_value_overlap,
    subspace_overlap,
    right_subspace_overlap,
    # Efficient batched SVD computation
    compute_global_svd_metrics,
    compute_layerwise_stacked_svd_metrics,
    compute_perlayer_tensor_svd_metrics,
    compute_all_svd_metrics,
    GLOBAL_SVD_METRICS,
    LAYERWISE_STACKED_SVD_METRICS,
    PERLAYER_TENSOR_SVD_METRICS,
    ALL_SVD_METRICS,
)

__all__ = [
    "METRIC_REGISTRY",
    "compute_metric",
    "compute_all_metrics",
    "compute_metric_per_layer",
    "compute_metric_layer_wise_avg",
    "flatten_task_dict",
    "task_vector_cosine_similarity",
    "task_vector_l2_distance",
    "task_vector_dot_product",
    "weight_space_angle",
    "task_vector_magnitude_ratio",
    "singular_value_overlap",
    "subspace_overlap",
    "right_subspace_overlap",
    # Efficient batched SVD computation
    "compute_global_svd_metrics",
    "compute_layerwise_stacked_svd_metrics",
    "compute_perlayer_tensor_svd_metrics",
    "compute_all_svd_metrics",
    "GLOBAL_SVD_METRICS",
    "LAYERWISE_STACKED_SVD_METRICS",
    "PERLAYER_TENSOR_SVD_METRICS",
    "ALL_SVD_METRICS",
]
